apiVersion: v1
kind: Service
metadata:
  name: golang-local-kubernetes
spec:
  selector:
    app: golang-local-kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort